apiVersion: v1
kind: Service
metadata:
  name: nginx
  # Service labels
  labels:
    project: roboshop
    environment: dev
spec:
  # Service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: frontend
    component: frontend
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # Container port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx # Pod Name
  labels:
    project: roboshop
    environment: dev
    component: frontend
    tier: frontend
spec:
  containers:
  - name: nginx # Container name
    image: nginx # By default it will get from docker hub